defaults: &defaults
  blog_name: "SIMPLE BLOG"
  blog_description: "I seldom talk!"

development:
  <<: *defaults
  host: "localhost:3000"

test:
  <<: *defaults
  host: "localhost:3000"

production:
  <<: *defaults
  host: "the.host.com"
