defaults: &defaults
  blog_name: "Livoras's Blog"
  blog_description: "I seldom talk!"

development:
  <<: *defaults
  host: "localhost:3000"

test:
  <<: *defaults
  host: "localhost:3000"

production:
  <<: *defaults
  host: "blog.livoras.com"
