# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce107b96ff04643d75ef816d19f1a001327e8c458b6106bd4615f0962760716fe40378fccb9a21922d12e5a727f486bd08f978c9653f6c25473273b8131f1c0f

test:
  secret_key_base: af94565f4e1fb8b95be1b448e93b794af8e9e230ffcb2425010d54be9ace77a8d635d7dd5f79cfaf9d3440ddf587a86558bcb16a02673832e8c35ad53cfb5710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
